//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ChildInfo
    {
        public int ChildId { get; set; }
        public string ChildName { get; set; }
        public string ChildAlternativeName { get; set; }
        public Nullable<int> Age { get; set; }
        public string Sex { get; set; }
        public string Build { get; set; }
        public string HairColor { get; set; }
        public string EyeColor { get; set; }
        public string Glases { get; set; }
        public string IdentityMark { get; set; }
        public string Shirt { get; set; }
        public string Trouser_Skert { get; set; }
        public string imageUrl { get; set; }
        public string IsApproved { get; set; }
        public string Description { get; set; }
    }
}
