//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ParentInformation
    {
        public int ChildId { get; set; }
        public string Report_by_Person_Name { get; set; }
        public Nullable<long> CNIC { get; set; }
        public string Address { get; set; }
        public string Phone_ { get; set; }
        public string Email { get; set; }
        public string Relation_to_Missing_Child { get; set; }
        public string Father_Name { get; set; }
        public string Address_Of_Child { get; set; }
        public string Phone__ { get; set; }
        public Nullable<System.DateTime> Report_Created_Date_Time { get; set; }
        public string PoliceStationEmail { get; set; }
        public string PoliceStation { get; set; }
        public string ChildMissingLocation { get; set; }
    }
}
