//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_SuspectPersonInformation
    {
        public int Id { get; set; }
        public string Name { get; set; }
         [Required]
        [Range(10, 100, ErrorMessage = "Please enter (Guess/Known) the age.Between 10 to 100")]
        public Nullable<int> Age { get; set; }
        [Required]
        public string Gender { get; set; }
        [Required]
        public string Build { get; set; }
        public Nullable<int> Height { get; set; }
        public string HairColor { get; set; }
        public string EyeColor { get; set; }
        public string Complexion { get; set; }
        public string Glasses { get; set; }
        public string Beard { get; set; }
        public string Mustache { get; set; }
        public Nullable<System.DateTime> Crime_Date_Time { get; set; }
        public string InformationAboutCrime { get; set; }
        public string NearestPoliceStation { get; set; }
    }
}
